/*
 * cp_likelihood.c
 *
 * Calculates likelihood for an arbitrary number of changepoint
 * locations and open probabilities.
 *
 * Ivo Siekmann, 20/11/2013
 *
 * 
 * Compile with:
 *
 * gcc -Wall -pedantic -o filename filename.c
 *
 */

#include <stdio.h>
#include "mp_mcmc.h"
#include "mp_parameter.h"
#include "mp_proposal.h"

#include "cp_proposal.h"
#include "cp_prior.h"

/* Likelihood that the open/closed events between k0 and k1 have been
   generated by a Bernoulli process with open probability p.*/
double logBernoulli(double p,const int *CDF, int k0, int k1, 
		    double alpha, double beta) {
  int succIn1=succInterval(CDF,k0,k1);
  int failIn1=failInterval(CDF,k0,k1);
  double priorS=alpha+1, priorF=beta+1;

  return (succIn1+priorS)*log(p)+(failIn1+priorF)*log(1-p);
}


/* proposal likelihood */
double propLikelihood(int nProp,
		      const parameters *p, int nP,
		      const intparameters *ip, int nIP) {
  int i, kI, kPred=0;
  double pI, L=0;
  double alpha=getAlpha(), beta=getBeta();
  const int *CDFdata=getData();

  /* Likelihood that the trace has NO changepoint */
  if(nProp==0) {
    int n=getNdata();
    int succ=CDFdata[n-1], fail=n-succ;

    pI=getProposal(p, 0);
    return (succ+alpha+1)*log(pI) + (fail+beta+1)*log(1-pI);
  }

  /* Likelihood if the trace has one or more changepoints */
  for(i=0; i<nProp; i++) {
    kI=getIntProposal(ip,i);
    pI=getProposal(p, i);
    L+=logBernoulli(pI,CDFdata, kPred, kI, alpha, beta);
    kPred=kI;
  }

  /* There's still one probability left... for the last segment. */
  pI=getProposal(p, i);
  L+=logBernoulli(pI,CDFdata, kI, getNdata(), alpha, beta);
  return L;
}

/* Parameter likelihood */
double parLikelihood(int nPar,
		     const parameters *p, int nP,
		     const intparameters *ip, int nIP) {
  int i, kI, kPred=0;
  double pI, L=0;
  double alpha=getAlpha(), beta = getBeta();
  const int *CDFdata=getData();

  /* Likelihood that the trace has NO changepoint */
  if(nPar==0) {
    int n=getNdata();
    int succ=CDFdata[n-1], fail=n-succ;
    pI=getParameter(p, 0);
    return (succ+alpha+1)*log(pI) + (fail+beta+1)*log(1-pI);
  }

  /* Likelihood if the trace has one or more changepoints */
  for(i=0; i<nPar; i++) {
    kI=getIntParameter(ip,i);
    pI=getParameter(p, i);
    L+=logBernoulli(pI,CDFdata, kPred, kI, alpha, beta);
    kPred=kI;
  }

  /* Theres still one probability left... for the last segment. */
  pI=getParameter(p, i);
  L+=logBernoulli(pI,CDFdata, kI, getNdata(), alpha, beta);

  return L;
}


/* Calculates likelihood for given locations of changepoints and open
   probabilities. */
double dLikelihood(const parameters *p,
		   int actP, int propP, int nP,
		   const intparameters *ip,
		   int actIP, int propIP, int nIP,
		   likelihood *L) {
  double propL=propLikelihood(propIP,p,nP,ip,nIP);
  double parL=parLikelihood(actIP,p,nP,ip,nIP);
  double propScale=log(getProposalScale());

  /* Calculate likelihood of current changepoint configurations and
     open probabilities, add scaling factor for proposal.*/
  setPosterior(L,parL, propL+propScale);

  return propL-parL;
}

/* Calculates likelihood for given locations of changepoints and open
   probabilities. */
double dFixedLikelihood(const parameters *p, int nP,
		       const intparameters *ip,int nIP,
		       likelihood *L) {
  double propL=propLikelihood(nIP,p,nP,ip,nIP);
  double parL=parLikelihood(nIP,p,nP,ip,nIP);

  /* Calculate likelihood of current changepoint configurations and
     open probabilities, add scaling factor for proposal.*/
  setPosterior(L,parL, propL);

  return propL-parL;
}
